# Docker compose yml config
# Note this dependes on the PWD context so make sure you run from the right relative path
# to the repository. If not there will be empty directories created in the docker containers instead of files...
# to name just one problem. So run docker compose while in the same directory as this file.

version: '3.7'
#version: "3.5"

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_service
        volumes:
            #- /tmp/dc-test-db:/var/lib/mysql # Disabled for non permanence
            - ${PWD}/init.sql:/data/application/init.sql
        command: --init-file /data/application/init.sql

        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: removed
            MYSQL_USER: kaicalib_db_user
            MYSQL_PASSWORD: removed


    tomcat:
        image: tomcat:9-jre10
        container_name: tomcat_service
        ports:
            - "8080:8080"
        volumes:
            - ${PWD}/build/libs/kaicalib-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/kaicalib.war
        depends_on:
            - mariadb
